### ISSUE TITLE
Can pytest parameterize be used with pytest-cpp

### ISSUE THREAD

**Issue by brendan-simon-indt** [pytest-dev/pytest-cpp#144]
Can pytest's parameterize feature be used with pytest-cpp, to run a test with lots of different input stimulus and expected results?

**Comment by nicoddemus** [comment]
Hi @brendan-simon-indt, 

No, pytest-cpp only acts as a wrapper around the C++ testing framework, basically calling the C++ test runner as a subprocess and wrapping the results in a form that pytest understands. It cannot influence how the tests themselves are executed (for example, changing inputs as you mention).
