### ISSUE TITLE
Type-Parametrized Gtests failure

### ISSUE THREAD

**Issue by joarbe** [pytest-dev/pytest-cpp#17]
When using pytest-cpp-0.3.1 runner against type-parametrized google-test executable I always get the following failure:

        MatrixTest/0.  # TypeParam = Matrix<float>Equal ______________________________
        Internal Error: could not find test MatrixTest/0.  # TypeParam = Matrix<float>Equal in results:
        unknown file:0: C++ failure

My guess is that the parser code used to discover gtests is not robust to type-parametrized tests.
A fix for this would be highly appreciated.

It can be reproduced with gtest-1.7.0

Thanks,
joar

**Comment by nicoddemus** [comment]
Thanks for the report! I will work on it. :smile:

**Comment by nicoddemus** [comment]
This has been fixed, thanks again. I will make a `0.4.0` release shortly. :smile:

**Comment by joarbe** [comment]
thank you so much Bruno, I'll update soon to get this functionality!
Great package the one you're building!
Jordi

2015-08-24 5:21 GMT+02:00 Bruno Oliveira <notifications@github.com>:

**Comment by nicoddemus** [comment]
Release [0.4](https://goo.gl/k8m6jK) is out. :smile:
