### ISSUE TITLE
Ignore python test files maybe?

### ISSUE THREAD

**Issue by fj128** [pytest-dev/pytest-cpp#39]
pytest version 4.0.0, pytest-cpp-1.1.0

I like to make my test files executable sometimes, so that I can run them directly. Unfortunately this interacts with pytest-cpp in a noticeably annoying way:

    $ cat test_sample.py
    #!/usr/bin/env pytest
    import pytest

    def test_thing():
        pass

    $ time pytest test_sample.py
    
    [snip]

    real    0m1.026s
    user    0m0.902s
    sys     0m0.121s

    $ chmod +x test_sample.py

    $ time pytest test_sample.py
    
    [snip]

    real    0m3.152s
    user    0m2.762s
    sys     0m0.389s

Every time pytest-cpp sees an executable file with a test-like name, it tries to execute it twice (separately checking for boost/google tests). If the file is a python script that imports pytest, the whole thing ends up taking 3 times as much time as usual just for initialization.

I don't know the details of pytest plugin architecture, so I'm not sure which is the best way to fix it (if any, maybe I should just not do that thing, as the joke goes): make this plugin explicitly skip `*.py` files or maybe pytest itself shouldn't give the files it successfully imported and registered to any further plugins?

**Comment by nicoddemus** [comment]
Hi @fj128,

Thanks for writing up. I think the proper way to fix this is like you suggest, to just skip `*.py` files. I would be happy to review and merge a PR for this. 👍

**Comment by fj128** [comment]
@elkin `cpp_files`  uses `path.fnmatch` which doesn't allow you to say "all files starting with 'test_' but not ending with '.py'".

I'll try to make a patch, I just hope nobody out there creates boost-test executables with ".py" extension.

**Comment by elkin** [comment]
> cpp_files uses path.fnmatch which doesn't allow you to say "all files starting with 'test_' but not ending with '.py'".

@fj128 that’s right. But may be it would be more helpful to generalize your proposal a little bit. I mean adding a new parameter like `cpp_skip_files` or `cpp_ignored_files`. That parameter will also be a mask like `cpp_files`.

**Comment by fj128** [comment]
To celebrate this issue turning one year old, I finally made a fix and a pull request: #42

I ended up implementing a cpp_ignore_py_files option that's enabled by default and completely disables the attempts to detect if "*.py" files are boost/google tests. We should add a release note saying that this will break things for the people who give their cpptests .py extensions, so they should disable that option if they want to continue living their lives in depravity and mayhem.

I considered several alternatives: first of all, I thought about doing a magic number check to detect actual elfs/exes/whatever, apparently it's pretty easy even for more exotic architectures such as AIX or Solaris, but this approach had a fatal flaw: at work we had a bunch of cpp tests invoked via bash wrappers that did some necessary set up.

Then I thought about giving up and just strongly suggesting in the documentation to use a custom prefix different from usual pytests, such as `cpptest_*`. But then I discovered that this plugin (rightfully) mimics the general pytest behavior when given a file on the commandline: it ignores any masks and checks the file always. Which is annoying and means that I have to have an option that overrides that behavior on a higher level so to speak.

This point also applies to @elkin's proposal, but also I ideologically oppose implementing features that nobody asked for, _every_ line of code is a technical debt, it's just some lines bring more profit than they cost.

So here we are.

-----------

The pull request also contains a commit that fixes some stuff that doesn't work with modern boost and pytest. Also, you'd probably have to fix three more failing tests caused by slight boost::test output changes like "check ... failed" => "check ... has failed". I didn't want to do it myself because I don't know which version of boost you're going to get on your CI setup.

The last test in my test function is a bit of a trainwreck because of what I think is a pytest bug: when a test file is given on the commandline it tries to test it as a pytest even if our hook recognized it. Interestingly, earlier versions of pytest threw an exception complaining that there's more than one matching value for matchreport, current just returns a wrong one.

**Comment by nicoddemus** [comment]
Released in 1.2.0! Thanks @fj128!

**Comment by fj128** [comment]
Yay! Thank you, too.

I like the deadpan tone of the documentation for the feature.

**Comment by nicoddemus** [comment]
> I like the deadpan tone of the documentation for the feature.

Hmmm what do you mean?

**Comment by fj128** [comment]
I mean, hopefully most people would find the idea that someone has C++
executable files with .py extension hilarious (or terrifying), while the
documentation treats it as a matter of fact =)

**Comment by nicoddemus** [comment]
Oh i see hehehe
