### ISSUE TITLE
Add a way to use valgrind, catchsegv or similar tool

### ISSUE THREAD

**Issue by dajose** [pytest-dev/pytest-cpp#49]
Tools like valgrind and catchsegv are used in this way

```
valgrind --tool=memcheck gtest-binary
```

I think a way of using something like that would be to add a `pytest_addoption` on the `ini` like

```
[pytest]
harness = valgrind --tool=memcheck 
```

thoughts? recommendations?

**Comment by nicoddemus** [comment]
Hi @dajose, 

I think that would be useful and also simple to implement.

Just to bikesheeding a bit, the option should be `cpp_harness` to make its relation to the plugin clear.

I probably won't have time to get to this soon, but a PR would be welcome.

cc @tadeu

**Comment by dajose** [comment]
sure :) let me give it a try
