### ISSUE TITLE
Add support for Catch testing framework

### ISSUE THREAD

**Issue by ktbarrett** [pytest-dev/pytest-cpp#53]
[Catch](https://github.com/catchorg/Catch2) is a very popular unit testing library. Is it possible support may be added? Catch test executables support listing all test names; filtering tests; outputing in an easily parsable format (JUnit). Just following what the Google Test support is doing, it seems to support everything necessary.

**Comment by nicoddemus** [comment]
Hi @ktbarrett,

Support for Catch is certainly possible, and should be similar to the support we have for Boost.Test and Google Test.

**Comment by nicoddemus** [comment]
Fixed by #60.

**Comment by nicoddemus** [comment]
2.0.0 is out! 🎉

**Comment by ktbarrett** [comment]
Excellent! Thank you @salim-runsafe and @nicoddemus!
