### ISSUE TITLE
Key Error after upgrade to 2.1.0

### ISSUE THREAD

**Issue by janvonrickenbach** [pytest-dev/pytest-cpp#73]
After the upgrade to 2.1.0 I observe the following error:

```
    def _parse_xml(self, xml_filename):
        root = ElementTree.parse(xml_filename)
        result = []
        for test_suite in root.findall("testsuite"):
            test_suite_name = test_suite.attrib["name"]
            for test_case in test_suite.findall("testcase"):
                test_name = test_case.attrib["name"]
                failures = []
                failure_elements = test_case.findall("failure")
                for failure_elem in failure_elements:
                    failures.append(failure_elem.text)
                skippeds = []
>               if test_case.attrib["result"] == "skipped":
E               KeyError: 'result'

test_env\lib\site-packages\pytest_cpp\google.py:125: KeyError
```

It looks like replacing  test_case.attrib.get("result", None) with  test_case.attrib["result"]  is the issue: https://github.com/pytest-dev/pytest-cpp/commit/2a2f12568f0611c6263bf8de9420d59d6d7f4b32

**Comment by nicoddemus** [comment]
Hi @janvonrickenbach, 

indeed, thanks for the report!

cc  @neyrojasj

**Comment by neyrojasj** [comment]
Thanks for the heads-up @nicoddemus, @janvonrickenbach is there an easy way to trigger this issue?

**Comment by nicoddemus** [comment]
`2.1.1` released as a hot fix.

> is there an easy way to trigger this issue?

This would be great to have, as we can add a new test to the suite to avoid future regressions (like this one we just had).

**Comment by janvonrickenbach** [comment]
Thanks for the fix. Works as expected.

Not sure I can provide a simple way to trigger the issue. The project has a very basic setup. 

The only option apart from search directories we use is
junit_family = xunit2

in pytest.ini.
