### ISSUE TITLE
Error when using gtest arguments

### ISSUE THREAD

**Issue by ovidiuc88** [pytest-dev/pytest-cpp#84]
Hi,

I'm trying to run gtest binaries with pytes-cpp and I can't seem to find a way to use --gtest_filter properly. If I use only --gtest_repeat=x for example, it works fine, but if I try to use --gtest_filter I get 

```python
def run_test(self, executable, test_id, test_args=(), harness=None):
        harness = harness or []
        output = ""
        xml_filename = self._get_temp_xml_filename()
        args = harness + [
            executable,
            "--gtest_filter=" + test_id,
            "--gtest_output=xml:%s" % xml_filename,
        ]
        args.extend(test_args)
    
        try:
            output = subprocess.check_output(
                args, stderr=subprocess.STDOUT, universal_newlines=True
            )
        except subprocess.CalledProcessError as e:
            output = e.output
            if e.returncode != 1:
                msg = (
                    "Internal Error: calling {executable} "
                    "for test {test_id} failed (returncode={returncode}):\n"
                    "{output}"
                )
                failure = GoogleTestFailure(
                    msg.format(
                        executable=executable,
                        test_id=test_id,
                        output=e.output,
                        returncode=e.returncode,
                    )
                )
    
                return [failure], output
    
        results = self._parse_xml(xml_filename)
        os.remove(xml_filename)
        for (executed_test_id, failures, skipped) in results:
            if executed_test_id == test_id:
                if failures:
                    return [GoogleTestFailure(x) for x in failures], output
                elif skipped:
                    pytest.skip("\n".join(skipped))
                else:
                    return None, output
    
        msg = "Internal Error: could not find test " "{test_id} in results:\n{results}"
>       results_list = "\n".join(x for (x, f) in results)

/home/oci/.local/lib/python3.6/site-packages/pytest_cpp/google.py:106: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x7f45e1d26c18>

>   results_list = "\n".join(x for (x, f) in results)
E   ValueError: too many values to unpack (expected 2)`

in lib/python3.6/site-packages/pytest_cpp/google.py:106: ValueError
```

If I run the binary itself with the filters I am using, it works; so I don't think the filter themselves are the issue (though I thought so at the beginning).
Any ideas?

**Comment by ovidiuc88** [comment]
Hi @nicoddemus ,

I removed the actual names because they won't make sense to you anyway but I get this
`Internal Error: could not find *_current test_* in results:
*_what the filter should be looking for_* 
unknown file:0: C++ failure`

So it tries to find "name of running test" in "test I set in the filter" and that's fine, it should just say it does not match and move on without running anything. But what I get from the logs is that it runs the test I was trying to filter to begin with, fails with this internal error, moves on, runs the same test again, fails , moves on etc. 
So it feels to me the filter works but it runs it once for each test filtered out...if this makes sense :))

**Comment by nicoddemus** [comment]
Can you post the exact command line you are using? Feel free to redact any internal names, but replace them with function-like names, say `test_actual_app_name` to `test_foo` or something like that?

**Comment by nicoddemus** [comment]
You are using `cpp_arguments` to pass `--gtest_filter` correct?

If so, that will conflict with the plugin, because we list the tests inside the executables, and execute each in turn. If you pass `--gtest_filter` I think this will interfere with this functionality.

When using pytest-cpp, it is recommended to use pytest's own filtering flags (passing ids, `-k`, `-m`, etc) instead.

**Comment by ovidiuc88** [comment]
Correct! I will try using pytest filtering flags and get back to you asap! Thank you!
