### ISSUE TITLE
Add support of prefix-ish parameter to run executable

### ISSUE THREAD

**Issue by tujh-rf** [pytest-dev/pytest-cpp#89]
Hi (and Happy New Year)

I'm trying to use pytest-cpp to test multiplatform project.
One of my build target is Windows under Linux (using MinGW as compiler). It is also possible to use Linux to run Windows tests with wine.
I did try to specify cpp_harness parameter but it works only when the list of tests are known and to get that list from a gtest execurtable it is needed to run it first. And here I have an isssue, cpp_harness is not in use in 'list_tests' function and the function is trying to run executable as is.
From other hand I think it is not correct to use the same parameter as cpp_haness to get list of tests and to run each of test.

Maybe it will be usefull for other projects where an executable cannot be run directly and only via some kind of emulator layer.

**Comment by nicoddemus** [comment]
Happy new year!

Yeah makes sense. Perhaps we can add a `cpp_prefix` or something along that lines? Would be happy to review and merge a PR adding this support.

**Comment by nicoddemus** [comment]
Let me see if I got the workflow correctly:

1. You are on a Linux system.
2. You have a bunch of test binaries compiled for Windows.
3. You execute pytest on Linux, and you need to execute each test with a prefix (say `wine -exec test_foo.exe`).
4. So the problem is that the path given in https://github.com/pytest-dev/pytest-cpp/blob/ddf754a863246ac3b84eae680f38dcf00157851d/src/pytest_cpp/google.py#L76-L80 will not be compatible.

Is my understanding correct?

**Comment by tujh-rf** [comment]
> Is my understanding correct?
Your understanding is correct.

By default, Wine is creating reports in the current folder (./tmp/pytest-cppila67jk8/cpp-report.xml) instead of /tmp.

**Comment by tujh-rf** [comment]
Here is example project to play with: https://github.com/tujh-rf/pytest-cpp-example

**Comment by nicoddemus** [comment]
One thing I realized: what if we just also used `cpp_harness` for listing tests? That would allow this use case without the need for a new option.

@dajose would using the harness to list the tests be a problem for your workflow?

**Comment by nicoddemus** [comment]
@tujh-rf I think we can get around the directory problem if we write the XML to cwd:

```python
with tempfile.TemporaryDirectory(prefix="pytest-cpp", dir=os.getcwd()) as tmp_dir:
    xml_filename = os.path.join(tmp_dir, "cpp-report.xml")
```

So the filename will always be relative to the current directory and be valid in both OSs.

**Comment by tujh-rf** [comment]
> One thing I realized: what if we just also used `cpp_harness` for listing tests (before any subprocess execution really)? That would allow this use case without the need for a new option.

That was indeed my first triedge :)
And this will work as expected in my scenario, os if it will be fine for @dajose it will be fully fine to me.

**Comment by tujh-rf** [comment]
> So the filename will always be relative to the current directory and be valid in both OSs.

That's why I did ask your opinion, right now pytest-cpp is using global temporary folder and not a current directory. This solution will be absolutly perfect in my scenario.

**Comment by nicoddemus** [comment]
> That's why I did ask your opinion, right now pytest-cpp is using global temporary folder and not a current directory. This solution will be absolutly perfect in my scenario.

It might break some (admittedly rare) environments where the current directory is not writable, but we might try releasing this and see if anybody encounters a problem with this.

**Comment by dajose** [comment]
> One thing I realized: what if we just also used `cpp_harness` for listing tests (before any subprocess execution really)? That would allow this use case without the need for a new option.
> 
> @dajose would using the harness to list the tests be a problem for your workflow?

I think it will not break things (not totally sure) , but I have 2 concerns:

1. I use the `cpp_harness` to use processes like _valgrind_ which adds up execution time and complexity
2. what if the options for listing are different from the options needed to actually run the test?

**Comment by nicoddemus** [comment]
>  I use the cpp_harness to use processes like valgrind which adds up execution time and complexity

True, but I believe the added execution time should be negligible, compared to actual test execution.

> what if the options for listing are different from the options needed to actually run the test?

Indeed, but for your specific use case (`valgrind`), would they be different?

I think we can try our best to anticipate how this will work with other tools, but we might decided to look at the two use cases we have and use them as basis for a decision: we can always implement a new option later.

**Comment by dajose** [comment]
> Indeed, but for your specific use case (`valgrind`), would they be different?

not really

> I think we can try our best to anticipate how this will work with other tools, but we might decide to look at the two use cases we have and use them as basis for a decision: we can always implement a new option later.

I like this, we could add a config flag to opt out of the harness on test collection, something like "cpp_harness_collect: true" or a better name

**Comment by tujh-rf** [comment]
Sound good, I'll update my PR to handle this remarks.
